### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by srutisriram** [learn-co-curriculum/modules-reading#24]
There are quite a few typos in this and the previous lab (but not in the readme, in the KNOWLEDGE array in the previous lab and in the bin file in this one). I"m not sure how to fix those documents - I'd be happy to but not sure I know how. Just a head's up!

**Comment by AnnJohn** [comment]
thanks @srutisriram for raising this issue. We'll go and update, but if possible, could you send over some screenshots or note in which the lines/files the typos occur? thanks!
