### ISSUE TITLE
incomplete tests

### ISSUE THREAD

**Issue by srutisriram** [learn-co-curriculum/modules-reading#25]
These tests passing are dependent on the refactored FancyDance file, but in the kid.rb and ballerina.rb file, only want you to include the original Dance and MetaDancing modules, not the FancyDance ::InstanceMethods, which can get a little confusing.

**Comment by AnnJohn** [comment]
thanks @srutisriram for raising this!

@ruchiramani can you look into this issues above?

**Comment by AnnJohn** [comment]
@PeterBell no rush but here's an earlier issue from the full-stack curriculum. thanks!

**Comment by PeterBell** [comment]
Hey @aturkewi would you mind having a look at this and suggesting a fix - as an issue comment if you're not sure about the best approach or just submit a PR if you feel like you've got a handle on what to do?
