### ISSUE TITLE
"Ballerina" vs. "Dancer"

### ISSUE THREAD

**Issue by pletcher** [learn-co-curriculum/modules-reading#29]
"Mikhail Baryshnikov" probably wouldn't consider himself a ballerina (even in a world with a deconstructed gender binary).

Also, the lab spells his name incorrectly.

**Comment by ghost** [comment]
Agreed with your issue, Charles. Also I insist we correct the spelling for his name. :)

**Comment by SophieDeBenedetto** [comment]
fixed
