### ISSUE TITLE
ReadMe Solution NOT the same as Learn Solution

### ISSUE THREAD

**Issue by ndaniele** [learn-co-curriculum/modules-reading#32]
This lab seems to be written incorrectly.

the final section about how to use nested modules says that this is the correct code

class Ballerina
  extend FancyDance::ClassMethods
  include FancyDance::InstanceMethods
end
class Kid
  extend FancyDance::ClassMethods
  include FancyDance::InstanceMethods
end

but that actually raises syntax error when you run Learn. 

the code that passes the tests with no syntax errors is actually this:

class Kid
  extend MetaDancing
  include Dance

I am very confused by this and I'm left wondering which is the correct code to use going forward. the one in the ReadMe, which makes sense, but does't pass the tests, or the version that passes the tests. ..are the tests wrong? is the ReadMe wrong? some Admin definitely needs to take a look at this.

**Comment by SophieDeBenedetto** [comment]
hi @ndaniele, the code in the code-along is correct. remember that you need to add a file requirement once you define your `fancy_dance.rb` module. Once you define that module and want to mix it in to the `dancer.rb` and `kid.rb` files, you might require that file in `dancer.rb` and `kid.rb`, just like the other files are required there. I just added a note to that effect to the README. thanks!
