### ISSUE TITLE
just pointing out an item for this code along!

### ISSUE THREAD

**Issue by bmolina-nyc** [learn-co-curriculum/modules-reading#36]
There are not specs written for the part about extending modules to pass - so this might confuse a bunch of people because the code breaks entirely when coding the part about extending and including modules

class Ballerina
  extend FancyDance::ClassMethods
  include FancyDance::InstanceMethods
end    # coding along - if you add this everything errors out ....

**Comment by SophieDeBenedetto** [comment]
hi @bmolina-nyc, the test suite should continue to pass when you move on to the nested modules section and implement that code. Make sure you require the `fance_dance.rb` file in the files that contain the classes you are trying to mix that module in to.
