### ISSUE TITLE
Tests breaking; throws syntax errors even when given exact solution from solution branch. 

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/modules-reading#49]

**Comment by drakeltheryuujin** [comment]
Hi there,
I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue such as:
An expanded explanation of what's going on.
Steps to reproduce the issue.
Details about your environment.
What's your operating system? Which version?
Are you using the Learn IDE or a local development environment?
A stack trace of any errors--
I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Comment by justinddaniel** [comment]
This one's on me. I wrote the JIRA and issues before I was trained to report exactly what the problem was and what steps were taken to fix it. It has been too long and now I don't remember! I will report back if I encounter it again!
