### ISSUE TITLE
Confusing Codealong

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/modules-reading#51]
Hey, this is the most confusing Codealong yet. I think there's likely unnecessary code in my ruby files, but the Codealong only showed fragmented parts of the final code, so I don't know what code could be left out. I don't think that was the intention, so revisit this lesson.

**Comment by sgharms** [comment]
@helloamandamurphy 

1. Could you please specify what's confusing? Inclusion of modules a rather challenging concept, but I can't say I know where you lost your thread from the description provided. Please specify any bits that are difficult in (a) new issue(s).

2. Your [implementation](https://github.com/helloamandamurphy/modules-reading-v-000/commit/844498f2932e4e229749b51d6b01f3f8e73efef7). Is largely correct. You'll notice that in `Kid` and `Dancer` you include require `dance_module` but don't include or extend anything that it provides. This can be removed (note the specs still work).

Your `FancyDance::` modules are both coming from `fancy_dance.rb`. A very nice architecture would be to put them in `lib/fancy_dance/class_methods` and `lib/fancy_dance/instance_methods`, `require_relative` those, and then include them as you're doing. Try updating your code and make sure the specs still pass.
